name: Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'graalvm' # See 'Supported distributions' for available options
          java-version: '21'
      - run: mvn package & java -cp target/EspressoNI-1.0-SNAPSHOT.jar me.judge.Main